
backend:
  name: git-gateway
  branch: main
media_folder: content/uploads
public_folder: /uploads
collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'content/post'
    create: true
    slug: '{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Author', name: 'author', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Tags', name: 'tags', widget: 'list', required: false, allow_add: true  }
      - { label: 'Banner', name: 'banner', widget: 'file', required: false }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: 'Math Rendering', name: 'math', widget: 'boolean', default: false }
      - { label: 'Table of Contents', name: 'toc', widget: 'boolean', default: false }
