baseURL = "https://pyxill2.netlify.com/"
absURL= "https://pyxill2.netlify.com"
languageCode = "en-en"
title = "Pyxill 2"

contentdir = "content"
publishdir = "public"
builddrafts = false
theme = "pyxill2"
ignoreFiles = [ "\\.db$","\\.css$"]
pygmentsUseClassic=false
pygmentsStyle="dracula"
pygmentsCodefences=true
pygmentsOptions="linenos=false"
Paginate= 10
relativeURLs = false
canonifyURLs= true
enableEmoji = true


[indexes]
  category = "categories"
  tag = "tags"

[params]
  math_library="katex" #you can choose between katex or mathjax depending on your needs
  hostName = "https://pyxill2.netlify.com"
  toc= true
  absURL= "https://pyxill2.netlify.com"
  mainSections = ["post"]
  bg_color= "#3b4252"
  theme_color= "#4c566a"
  twitter_username = "gohugoio"
  paginate = 10
  description = "A minimal theme for Hugo"
  author = "Iacopo Moles"
  banner= "banner.png"
  staticman_api = "https://staticman-tutorial-hugo.herokuapp.com/v2/entry/IcpMoles/pyxback/main/comments" #Add staticman API URL to enable staticman comments
 #  RssUrl =  "https://example.com/rss"
  google_analytics_id = "73mlN4x3UZrTPxQ07EkDwLhKXo2GPTaP8JWKfg5vhWg"
  flattr_id = "e0v7jk"
  payment_pointer = "$ilp.uphold.com/kk3ZPeDi34nP"
  google_analytics_js = false
  js_privacy = true #uses locally hosted libraries instead of using their CDN
  footer_links = true #enables a footer navigation bar
  custom_navbar = true #makes the main navbar editable
  custom_footbar = true #maked the footbare editable 


[author]
  name = "Author"
	
[outputs]
  home = ["HTML", "AMP", "RSS"]
  page = ["HTML", "AMP", "RSS"]

  
[privacy]
  [privacy.instagram]
    disable = false
    simple = true
  [privacy.twitter]
    disable = false
    enableDNT = true
    simple = true
  [privacy.vimeo]
    disable = false
    simple = true
  [privacy.youtube]
    disable = false
    privacyEnhanced = true 
    
[build]
  writeStats = true
  

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      attribute = true
      autoHeadingID = true
      autoHeadingIDType = "github"
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = false
      xhtml = false
      

[menu]

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = -90

  [[menu.main]]
    name = "Archive"
    url = "/archives/"
    weight = -100

  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = -110

  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = -120

  [[menu.footer]]
    name = "Privacy Policy"
    url = "/privacy-policy/"
    weight = -90

  [[menu.footer]]
    name = " | "
    weight = -95

  [[menu.footer]]
    name = "Credits"
    url = "/credits/"
    weight = -100

  [[menu.footer]]
    name = "  | "
    weight = -105

  [[menu.footer]]
    name = "Admin"
    url = "/netlify/"
    weight = -110

