[build]
publish = "public"
command = "hugo --gc --minify"

[context.production.environment]
HUGO_VERSION = "0.91.2"
HUGO_ENV = "production"
HUGO_ISNETFLIFY = "true"
HUGO_BASEURL = "https://pyxill2.netlify.app/"

[context.split1]
command = "hugo --gc --minify --enableGitInfo"

[context.split1.environment]
HUGO_VERSION = "0.91.2"
HUGO_ENV = "production"

[context.deploy-preview]
command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.91.2"

[context.branch-deploy]
command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.91.2"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"

[[redirects]]
  from = "/*"
  to = "/404page/index.html"
  status = 404
